# Site wide configuration

title: "Kaushik's Blog"
description: "This is a description of my awesome site."
logo: images/profpic.ico
teaser: # 400x250 px default teaser image used in image archive grid
locale: en
url: #kaushikvasudevan.com
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: Kaushik Vasudevan
  email: thekashvan@gmail.com
  twitter: kaushikv24
  google:
    ad-client:
    ad-slot:
  bio: Metis Data Science FEllow
  avatar: https://avatars3.githubusercontent.com/u/20506172?v=3&s=466 # 160x160 px image for author byline
  disqus-shortname:


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
